For this exercises we have to build a processing pipeline that processes the movies dataset. Its not a matter of copy pasting code, but of taking decisions on how to deal with each variable.

### We load the dataset

In [1]:
import pandas as pd
import numpy as np

movies = pd.read_csv("data/movies.1.initial_process.csv")
movies = movies[movies.status=="Released"]
del movies["status"]
movies.head()

belongs_to_collection      budget   genre original_language  \
0  Father of the Bride Collection         NaN  Comedy                en   
1                             NaN         NaN   Drama                en   
2               Friday Collection   3500000.0  Comedy                en   
3                             NaN         NaN  Comedy                en   
4                             NaN  12000000.0  Comedy                en   

   popularity     production_company        production_country release_date  \
0    8.387519  Sandollar Productions  United States of America   1995-02-10   
1    0.894647                Miramax              South Africa   1995-12-15   
2   14.569650        New Line Cinema  United States of America   1995-04-26   
3    8.963037     Paramount Pictures  United States of America   1996-02-01   
4    9.592265     Universal Pictures  United States of America   1996-02-16   

      revenue  runtime                        title  vote_average  vote_count  
0  76578911.0    106.0  Father of the Bride Part II           5.7       173.0  
1    676525.0    106.0     Cry, the Beloved Country           6.7        13.0  
2  28215918.0     91.0                       Friday           7.0       513.0  
3        32.0     87.0                  Black Sheep           6.0       124.0  
4  41205099.0     92.0                Happy Gilmore           6.5       767.0

In [2]:
#check the data types of all the columns here and see the types of pipelines you can use
movies.dtypes

belongs_to_collection     object
budget                   float64
genre                     object
original_language         object
popularity               float64
production_company        object
production_country        object
release_date              object
revenue                  float64
runtime                  float64
title                     object
vote_average             float64
vote_count               float64
dtype: object

In [3]:
#Check the columns of the numerical dataframes that have a null value, and count them 
movies.isnull().values.any()
null_columns=movies.columns[movies.isnull().any()]
movies[null_columns].isnull().sum()

belongs_to_collection    1155
budget                    580
genre                      46
production_company        200
production_country         98
revenue                   137
runtime                     7
dtype: int64

This shows that the revenue has some values that are null. How shall we handle them? We drop those

In [4]:
movies = movies[movies.revenue > 0]
movies.head(50)


belongs_to_collection      budget            genre  \
0    Father of the Bride Collection         NaN           Comedy   
1                               NaN         NaN            Drama   
2                 Friday Collection   3500000.0           Comedy   
3                               NaN         NaN           Comedy   
4                               NaN  12000000.0           Comedy   
5                               NaN         NaN           Comedy   
6                               NaN  31000000.0           Comedy   
7                               NaN  52000000.0            Drama   
8   Brooklyn Cigar Store Collection   2000000.0           Comedy   
9                               NaN         NaN      Documentary   
10                              NaN  90000000.0  Science Fiction   
11                              NaN         NaN           Comedy   
12                              NaN    150000.0           Comedy   
13                              NaN         NaN           Comedy   
14                              NaN  14000000.0         Thriller   
15                              NaN         NaN           Comedy   
16                              NaN  10000000.0           Comedy   
17                Clerks Collection     27000.0           Comedy   
18       Dumb and Dumber Collection  16000000.0           Comedy   
19                              NaN    700000.0      Documentary   
20                              NaN  17000000.0            Drama   
21    Once were Warriors Collection         NaN            Drama   
22             Swan Princess Series  35000000.0        Animation   
23                              NaN         NaN           Comedy   
24                              NaN         NaN            Drama   
25                              NaN  11500000.0            Drama   
26                              NaN         NaN           Comedy   
27                              NaN         NaN           Comedy   
28                              NaN         NaN           Comedy   
29                              NaN         NaN            Drama   
30        The Karate Kid Collection  12000000.0        Adventure   
31                              NaN  26000000.0            Drama   
32                              NaN         NaN            Drama   
33                              NaN  11000000.0           Comedy   
34                              NaN  12000000.0            Drama   
35                              NaN         NaN            Drama   
36              Candyman Collection         NaN           Horror   
37                              NaN  12000000.0           Comedy   
38                              NaN         NaN           Comedy   
39           DragonHeart Collection  57000000.0          Fantasy   
40               The Apu Collection         NaN            Drama   
41               The Apu Collection         NaN            Drama   
42                              NaN   9000000.0  Science Fiction   
43                              NaN  27000000.0           Comedy   
44                              NaN  26000000.0           Comedy   
45                              NaN         NaN           Comedy   
46                              NaN   1752000.0            Drama   
47                              NaN   1400000.0            Drama   
48                              NaN         1.0            Drama   
49           Living Dead Collection    114000.0           Horror   

   original_language  popularity                      production_company  \
0                 en    8.387519                   Sandollar Productions   
1                 en    0.894647                                 Miramax   
2                 en   14.569650                         New Line Cinema   
3                 en    8.963037                      Paramount Pictures   
4                 en    9.592265                      Universal Pictures   
5                 en    0.540436                                     NaN   
6            

In [5]:
target_var = "revenue"
numerical_cols = movies.drop(columns=target_var).select_dtypes(np.number).columns

### Create a Pipeline that process the dataset. You have to make sure you deal accordingly with numerical, categorical and text variables.

In [59]:
#for the numerical datatypes
from sklearn import preprocessing, feature_extraction

#use the imputer's to fill up any missing data with the mean
imputer = preprocessing.Imputer(strategy="mean")
scaler = preprocessing.StandardScaler()

In [36]:
from sklearn.pipeline import make_pipeline

In [37]:
numerical_pipeline = make_pipeline(imputer,scaler)

In [38]:
numerical_pipeline

Pipeline(memory=None,
     steps=[('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_frequent',
    verbose=0)), ('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True))])

In [39]:
numerical_pipeline.fit_transform(movies[numerical_cols])

array([[ 0.08021286,  0.3814959 ,  0.10466098, -0.3267635 , -0.22703182],
       [ 0.08021286, -1.03915849,  0.10466098,  0.43720626, -0.53866313],
       [-0.8874011 ,  1.55363278, -0.62659035,  0.66639719,  0.43518473],
       ..., 
       [ 0.08021286, -1.12276277, -0.28533973, -1.54911512, -0.54450622],
       [-0.15436022,  0.65775164,  0.15341107,  0.28441231,  3.12495252],
       [ 0.08021286,  0.41578691, -0.38283991,  0.36080929,  0.04564558]])

### Transform the dataset

In [40]:
from sklearn.base import BaseEstimator

class ColumnSelector(BaseEstimator):
    def __init__(self, cols=None, drop_axis=False):
        self.cols = cols
        self.drop_axis = drop_axis

    def fit_transform(self, X, y=None):
        return self.transform(X=X, y=y)

    def transform(self, X, y=None):
        if hasattr(X, 'loc'):
            #only pandas dataframes have the method loc
            t = X.loc[:, self.cols].values
        else:
            # its a numpy array
            t = X[:, self.cols]

        if t.shape[-1] == 1 and self.drop_axis:
            t = t.reshape(-1)
        if len(t.shape) == 1 and not self.drop_axis:
            t = t[:, np.newaxis]
        return t

    def fit(self, X, y=None):
        return self

In [41]:
numerical_col_selector = ColumnSelector(cols=numerical_cols)

In [42]:
numerical_col_selector.fit_transform(movies)

array([[             nan,   8.38751900e+00,   1.06000000e+02,
          5.70000000e+00,   1.73000000e+02],
       [             nan,   8.94647000e-01,   1.06000000e+02,
          6.70000000e+00,   1.30000000e+01],
       [  3.50000000e+06,   1.45696500e+01,   9.10000000e+01,
          7.00000000e+00,   5.13000000e+02],
       ..., 
       [             nan,   4.53698000e-01,   9.80000000e+01,
          4.10000000e+00,   1.00000000e+01],
       [  1.60000000e+07,   9.84455800e+00,   1.07000000e+02,
          6.50000000e+00,   1.89400000e+03],
       [             nan,   8.56837800e+00,   9.60000000e+01,
          6.60000000e+00,   3.13000000e+02]])

In [43]:
numerical_pipeline =  make_pipeline( numerical_col_selector, imputer, scaler)

In [44]:
numerical_pipeline.fit_transform(movies)

array([[ 0.08021286,  0.3814959 ,  0.10466098, -0.3267635 , -0.22703182],
       [ 0.08021286, -1.03915849,  0.10466098,  0.43720626, -0.53866313],
       [-0.8874011 ,  1.55363278, -0.62659035,  0.66639719,  0.43518473],
       ..., 
       [ 0.08021286, -1.12276277, -0.28533973, -1.54911512, -0.54450622],
       [-0.15436022,  0.65775164,  0.15341107,  0.28441231,  3.12495252],
       [ 0.08021286,  0.41578691, -0.38283991,  0.36080929,  0.04564558]])

##Make the movie name a text column, to check the weightage of the words in the title

In [45]:
#text_col --> movie name
text_col = ["title"]

In [46]:
movies[text_col].head(5)

title
0  Father of the Bride Part II
1     Cry, the Beloved Country
2                       Friday
3                  Black Sheep
4                Happy Gilmore

In [47]:
from sklearn.feature_extraction.text import TfidfVectorizer 
from mlxtend.preprocessing import DenseTransformer

text_pipeline = make_pipeline(
    #ColumnSelector only works on a single column
  ColumnSelector(cols=text_col, drop_axis=True),
  TfidfVectorizer(),
    DenseTransformer()
)

In [48]:
text_pipeline.fit_transform(movies)

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [49]:
#Categorical Pipeline on the languages, genre, production country

from category_encoders import OneHotEncoder

In [50]:
categorical_col = ["original_language", "genre", "production_country"]

In [51]:
categorical_pipeline = make_pipeline(
    ColumnSelector(cols=categorical_col),
    OneHotEncoder()
)

categorical_pipeline.fit_transform(movies)[:5]

0_1  0_2  0_3  0_4  0_5  0_6  0_7  0_8  0_9  0_10  ...   2_25  2_26  2_27  \
0    1    0    0    0    0    0    0    0    0     0  ...      0     0     0   
1    1    0    0    0    0    0    0    0    0     0  ...      0     0     0   
2    1    0    0    0    0    0    0    0    0     0  ...      0     0     0   
3    1    0    0    0    0    0    0    0    0     0  ...      0     0     0   
4    1    0    0    0    0    0    0    0    0     0  ...      0     0     0   

   2_28  2_29  2_30  2_31  2_32  2_33  2_-1  
0     0     0     0     0     0     0     0  
1     0     0     0     0     0     0     0  
2     0     0     0     0     0     0     0  
3     0     0     0     0     0     0     0  
4     0     0     0     0     0     0     0  

[5 rows x 82 columns]

In [52]:
#Attempt 1, try a union

from sklearn.pipeline import make_union

In [53]:
processing_pipeline = make_union(numerical_pipeline,
    #text_pipeline,
    categorical_pipeline)

In [54]:
processing_pipeline

FeatureUnion(n_jobs=1,
       transformer_list=[('pipeline-1', Pipeline(memory=None,
     steps=[('columnselector', ColumnSelector(cols=Index(['budget', 'popularity', 'runtime', 'vote_average', 'vote_count'], dtype='object'),
        drop_axis=False)), ('imputer', Imputer(axis=0, copy=True, missing_values='NaN', strategy='most_f...e_unknown='impute',
       impute_missing=True, return_df=True, use_cat_names=False, verbose=0))]))],
       transformer_weights=None)

In [55]:
processing_pipeline.fit_transform(movies)

array([[ 0.08021286,  0.3814959 ,  0.10466098, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.08021286, -1.03915849,  0.10466098, ...,  0.        ,
         0.        ,  0.        ],
       [-0.8874011 ,  1.55363278, -0.62659035, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.08021286, -1.12276277, -0.28533973, ...,  0.        ,
         0.        ,  0.        ],
       [-0.15436022,  0.65775164,  0.15341107, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.08021286,  0.41578691, -0.38283991, ...,  0.        ,
         0.        ,  0.        ]])

### Create a Ridge estimator to predict a movies revenue based on the other features. What is the optimal value of alpha to minimize the RMSE? *Hint*: You can use validation curves to figure it out.

In [56]:
from sklearn.linear_model import LinearRegression

estimator = LinearRegression()
estimator_pipeline = make_pipeline(
    processing_pipeline,
    estimator
)

In [57]:
estimator_pipeline.fit(movies, movies[target_var])

#Then this means that the revenue has some Nan values. check it out

Pipeline(memory=None,
     steps=[('featureunion', FeatureUnion(n_jobs=1,
       transformer_list=[('pipeline-1', Pipeline(memory=None,
     steps=[('columnselector', ColumnSelector(cols=Index(['budget', 'popularity', 'runtime', 'vote_average', 'vote_count'], dtype='object'),
        drop_axis=False)), ('imputer', Imputer(axi... ('linearregression', LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False))])

In [58]:
list(estimator_pipeline.predict(movies)[:])

[36974592.0,
 675840.0,
 40173568.0,
 30261248.0,
 68952064.0,
 21417984.0,
 62001152.0,
 173121536.0,
 2818048.0,
 16920576.0,
 126296064.0,
 36073472.0,
 3592192.0,
 30142464.0,
 -296960.0,
 33587200.0,
 44906496.0,
 56508416.0,
 157143040.0,
 4558848.0,
 14696448.0,
 13688832.0,
 56682496.0,
 46178304.0,
 23080960.0,
 18776064.0,
 23048192.0,
 39096320.0,
 25399296.0,
 26681344.0,
 38830080.0,
 99020800.0,
 19929088.0,
 21843968.0,
 23347200.0,
 23599104.0,
 24385536.0,
 18354176.0,
 14757888.0,
 100499456.0,
 2230272.0,
 -90112.0,
 -8192.0,
 51458048.0,
 43155456.0,
 25550848.0,
 35627008.0,
 27873280.0,
 8675328.0,
 40785920.0,
 54366208.0,
 139591680.0,
 1081344.0,
 14589952.0,
 94404608.0,
 27181056.0,
 105213952.0,
 21495808.0,
 56242176.0,
 23437312.0,
 21209088.0,
 -1075200.0,
 10139648.0,
 6864896.0,
 -12869632.0,
 212242432.0,
 36851712.0,
 145342464.0,
 88567808.0,
 43245568.0,
 215089152.0,
 58793984.0,
 35704832.0,
 89313280.0,
 64610304.0,
 7911424.0,
 26996736.0,
 7455

### Remember when we did exploratory data analyses and we groupd the numerical variables into quintiles? That is a valid technique used in Machine Learning to expand a dataset, it is called [Binning or Bucketing](http://blog.yhat.com/tutorials/5-Feature-Engineering.html).

### Create your own transformer that given a numerical variable and a number of buckets returns the specificed quartile (so if we choose buckets = 4, it would return 1, 2,3 or 4 depending on each observation being on the 1st, 2nd, 3rd or 4th quartile).

### Try putting your bucket transformer into a pipeline to make sure it works, and check if it improves the performance of your model.

**Hint**: You can use `ColumnSelector` as a template, and you can check pandas `qcut` for the actual binning.